### ISSUE TITLE
IL2CPP build error

### ISSUE THREAD

**Issue by murray-walker** [Unity-Technologies/com.unity.reflect.viewer#8]
We're not able to build the latest version due to an IL2CPP issue. There's not much help on the forums for this so thought I'd flag it here.

My colleague and I are getting the same error - We believe we have the correct C++ compilers and Windows 10 SDKs installed in our IDEs.

Here is the error: 
>Exception: Unity.IL2CPP.Building.BuilderFailedException: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\bin\HostX64\x64\link.exe /out:"D:\Unity\Elements\com.unity.reflect.viewer\ReflectViewer\Library\il2cpp_cache\linkresult_08047B686B7BD39F21128EC75EC201AF\GameAssembly.dll" /ignore:4206 /DEBUG /INCREMENTAL:NO /LARGEADDRESSAWARE /NXCOMPAT /DYNAMICBASE /NOLOGO /TLBID:1 /OPT:REF /OPT:ICF /HIGHENTROPYVA /DLL /IGNORE:4104 /NODEFAULTLIB:uuid.lib "kernel32.lib" "user32.lib" "advapi32.lib" "ole32.lib" "oleaut32.lib" "Shell32.lib" "Crypt32.lib" "psapi.lib" "version.lib" "MsWSock.lib" "ws2_32.lib" "Iphlpapi.lib" "Dbghelp.lib" "D:\Unity 2019\2020.3.6f1\Editor\Data\PlaybackEngines\WindowsStandaloneSupport\Variations\win64_nondevelopment_il2cpp\baselib.dll.lib" /LIBPATH:"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\lib\x64" /LIBPATH:"C:\Program Files (x86)\Windows Kits\10\Lib\10.0.19041.0\um\x64" /LIBPATH:"C:\Program Files (x86)\Windows Kits\10\Lib\10.0.19041.0\ucrt\x64" /LIBPATH:"C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64" /SUBSYSTEM:WINDOWS @"C:\Users\murray.walker\AppData\Local\Temp\1\tmpC609.tmp"

>Creating library D:\Unity\Elements\com.unity.reflect.viewer\ReflectViewer\Library\il2cpp_cache\linkresult_08047B686B7BD39F21128EC75EC201AF\GameAssembly.lib and object D:\Unity\Elements\com.unity.reflect.viewer\ReflectViewer\Library\il2cpp_cache\linkresult_08047B686B7BD39F21128EC75EC201AF\GameAssembly.exp
325AB965448C1C41A3F35A8F5290F0DF.obj : error LNK2019: unresolved external symbol dlopen referenced in function Mono_dlopen_m7F2DE2CD0870AB15EEA4E0A0BA6C47044E74BB67
325AB965448C1C41A3F35A8F5290F0DF.obj : error LNK2019: unresolved external symbol dlerror referenced in function Mono_dlerror_m359ABCFD23D0EB5314DE2DFF8AB58CFE949BBABD
325AB965448C1C41A3F35A8F5290F0DF.obj : error LNK2019: unresolved external symbol dlsym referenced in function Mono_dlsym_m31A00C09F598C9D552A94628C2C28B3C7B04C2DD
D:\Unity\Elements\com.unity.reflect.viewer\ReflectViewer\Library\il2cpp_cache\linkresult_08047B686B7BD39F21128EC75EC201AF\GameAssembly.dll : fatal error LNK1120: 3 unresolved externals

   >at Unity.IL2CPP.Building.CppProgramBuilder.PostprocessObjectFiles(HashSet`1 objectFiles, CppToolChainContext toolChainContext)
   at Unity.IL2CPP.Building.CppProgramBuilder.Build(IBuildStatistics& statistics)
   at il2cpp.Compilation.CompilationDriver.Run(RuntimePlatform platform, BuildingOptions buildingOptions, ReadOnlyCollection`1 matchedAssemblyMethodSourceFiles)
   at il2cpp.Program.DoRun(String[] args, RuntimePlatform platform, BuildingOptions buildingOptions, Boolean throwExceptions)
UnityEditorInternal.Runner.RunProgram (UnityEditor.Utils.Program p, System.String exe, System.String args, System.String workingDirectory, UnityEditor.Scripting.Compilers.CompilerOutputParserBase parser) (at <e09fc44b2b464346872ad04477f51ab1>:0)
UnityEditorInternal.Runner.RunManagedProgram (System.String exe, System.String args, System.String workingDirectory, UnityEditor.Scripting.Compilers.CompilerOutputParserBase parser, System.Action`1[T] setupStartInfo) (at <e09fc44b2b464346872ad04477f51ab1>:0)
UnityEditorInternal.IL2CPPBuilder.RunIl2CppWithArguments (System.Collections.Generic.List`1[T] arguments, System.Action`1[T] setupStartInfo) (at <e09fc44b2b464346872ad04477f51ab1>:0)
UnityEditorInternal.IL2CPPBuilder.ConvertPlayerDlltoCpp (UnityEditor.Il2Cpp.Il2CppBuildPipelineData data) (at <e09fc44b2b464346872ad04477f51ab1>:0)
UnityEditorInternal.IL2CPPBuilder.Run () (at <e09fc44b2b464346872ad04477f51ab1>:0)
UnityEditorInternal.IL2CPPUtils.RunIl2Cpp (System.String stagingAreaData, UnityEditorInternal.IIl2CppPlatformProvider platformProvider, System.Action`1[T] modifyOutputBeforeCompile, UnityEditor.RuntimeClassRegistry runtimeClassRegistry) (at <e09fc44b2b464346872ad04477f51ab1>:0)
DesktopStandalonePostProcessor.RunIL2CPP (UnityEditor.Modules.BuildPostProcessArgs args, UnityEditorInternal.IIl2CppPlatformProvider il2cppPlatformProvider, System.Collections.Generic.List`1[T] cppPlugins) (at <e09fc44b2b464346872ad04477f51ab1>:0)
DesktopStandalonePostProcessor.SetupStagingArea (UnityEditor.Modules.BuildPostProcessArgs args, System.Collections.Generic.HashSet`1[T] filesToNotOverwrite) (at <e09fc44b2b464346872ad04477f51ab1>:0)
DesktopStandalonePostProcessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args) (at <e09fc44b2b464346872ad04477f51ab1>:0)
Rethrow as BuildFailedException: Exception of type 'UnityEditor.Build.BuildFailedException' was thrown.
DesktopStandalonePostProcessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args) (at <e09fc44b2b464346872ad04477f51ab1>:0)
UnityEditor.Modules.DefaultBuildPostprocessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args, UnityEditor.BuildProperties& outProperties) (at <e09fc44b2b464346872ad04477f51ab1>:0)
UnityEditor.PostprocessBuildPlayer.Postprocess (UnityEditor.BuildTargetGroup targetGroup, UnityEditor.BuildTarget target, System.String installPath, System.String companyName, System.String productName, System.Int32 width, System.Int32 height, UnityEditor.BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport report) (at <e09fc44b2b464346872ad04477f51ab1>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)

**Comment by indigoray** [comment]
I have the same issue.

**Comment by murray-walker** [comment]
> 
> 
> I have the same issue.

A mono build seems to work fine. I'm just going with that till this issue is addressed.

**Comment by JeroenTekle** [comment]
Having the same issue here, would like to build il2cpp to test performance gains.

**Comment by JoRangers** [comment]
I have the same probleme with the last version available on github.

If I switch to mono, I can build.

**Comment by gamefabcn** [comment]
不要使用开发者的debug

**Comment by saraskul** [comment]
I am facing the same issue, the alternative is going for a mono build, if there are any solutions for this please let me know, ty
